import { MetadataObject } from './IMetadata';

export const fileMetadataKeys: ReadonlyArray<keyof MetadataObject> = [
  'atime',
  'atimeMs',
  'birthtime',
  'birthtimeMs',
  'blksize',
  'blocks',
  'bytes',
  'ctime',
  'ctimeMs',
  'dev',
  'gid',
  'ino',
  'isBlockDevice',
  'isCharacterDevice',
  'isDirectory',
  'isFIFO',
  'isFile',
  'isSocket',
  'isSymbolicLink',
  'mode',
  'mtime',
  'nlink',
  'rdev',
  'size',
  'uid',
];
